### ISSUE TITLE
Native VotingKey file generation

### ISSUE THREAD

**Issue by fboucquez** [symbol/symbol-bootstrap#169]
Instead of using catapult tools via docker run, bootstrap should generate the voting key natively in typescript.

This will:

- Speed up the config
- Remove docker from the requirement

This is pretty much a must-have if we want to bootstrap offline without requiring the node admin to also install catapult tools in the offline machine. 

@gimer , could you guide me? Where can I  find source code and docs to implement the catapult.tools.votingkey in typescript? Is it too complicated?

**Comment by gimer** [comment]
first you have a header:
start-epoch (8b),
end-epoch (8b),
last key identifier (8b) - for fresh file this is `0xFFFF'FFFF'FFFF'FFFF` (a.k.a. `Invalid_Id`)
last wipe key identifier (8b) - again, for fresh file this is `0xFFFF'FFFF'FFFF'FFFF` (`Invalid_Id`)
root public key (32b) - this is root public key that is getting announced via vote link tx
start-epoch (8b), \  those two are exactly same one, as top level, reason is this was earlier a tree,
end-epoch (8b), /   and each level holds this separately, so we left it as is

what follows are bound keys, there are `(end - start + 1)` of them.
each key is:
random PRIVATE key (32b)
signature (64b)

now the signature is usual signature done using ROOT private key on a following data:
(public key (32b), identifier (8b))

root private key is discarded after file is created.

identifier is simply epoch, but, most importantly keys are written in **REVERSE** order.

i.e. say your start-epoch = 2, end-epoch = 42
header:
`2, 42, ff.., ff..., (root pub), 2, 42`
keys:
`(priv key 42, sig 42), (priv key 41, sig 31), ..., (priv key 2, sig 2)`

every priv key should be **cryptographically random**,
