### ISSUE TITLE
Unable to update voting keys with the command updateVotingKeys

### ISSUE THREAD

**Issue by ichizero** [symbol/symbol-bootstrap#294]
**Describe the bug**

In v1.0.8, `symbol-bootstrap updateVotingKeys` fails to update voting keys with a following error.

> Error: Network preset could not be resolved!

I checked `target/preset.yml`, and the preset line is correctly existing as mainnet.

```yaml
version: 1
preset: mainnet
...
```

When I deleted the preset field, I got another error.

> Error: ENOENT: no such file or directory, open '/usr/lib/node_modules/symbol-bootstrap/presets/undefined/network.yml'
    Code: ENOENT

I think the condition for determining when there is no network preset is incorrect.

https://github.com/symbol/symbol-bootstrap/blob/7570872a954352e7b1b1f46d8dd2deddc624e9f4/src/commands/updateVotingKeys.ts#L62-L69

**To Reproduce**
To reproduce the behavior:

```zsh
mkdir debug && cd debug
symbol-bootstrap config
symbol-bootstrap updateVotingKeys
```

**Expected behavior**

`symbol-bootstrap updateVotingKeys` should updates voting keys correctly.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Tool Version
   - symbol-bootstrap v1.0.8

**Comment by fboucquez** [comment]
have you tried `symbol-bootstrap config --upgrade`

**Comment by fboucquez** [comment]
you are right, this is a bug.

**Comment by fboucquez** [comment]
Thanks for the issue and bug fix!
1.0.9 release hot fixes it.
